[package]
name = "fraq-shader-shared"
version = "0.1.0"
edition = "2018"

[dependencies]
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", features = ["glam"] }
bytemuck = { version = "1", features = ["derive"] }

[features]
default = []
std = []
